name: SAST Security Scan

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]
  schedule:
    - cron: '0 0 * * 0'  # Еженедельное сканирование

jobs:
  sast-php:
    name: SAST PHP (PHPStan & Psalm)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: composer
      
      - name: Install PHP dependencies
        run: |
          cd ui  # Переходим в директорию с PHP-кодом Zabbix
          composer install --no-progress --no-interaction
      
      - name: Run PHPStan (Static Analysis)
        run: |
          cd ui
          ./vendor/bin/phpstan analyse app/ classes/ --level=8 --error-format=github > phpstan-results.txt || true
      
      - name: Run Psalm (Security Analysis)
        run: |
          cd ui
          ./vendor/bin/psalm --shepherd --stats --output-format=github > psalm-results.txt || true
      
      - name: Upload PHP results
        uses: actions/upload-artifact@v4
        with:
          name: sast-php-results
          path: |
            ui/phpstan-results.txt
            ui/psalm-results.txt

  sast-c:
    name: SAST C/C++ (Cppcheck)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck
      
      - name: Run Cppcheck Analysis
        run: |
          # Анализируем основные исходники C, исключая сторонние библиотеки
          cppcheck --enable=all --suppress=missingIncludeSystem \
                   --inline-suppr --error-exitcode=0 \
                   src/ 2> cppcheck-results.txt
      
      - name: Upload C results
        uses: actions/upload-artifact@v4
        with:
          name: sast-c-results
          path: cppcheck-results.txt

  sast-go:
    name: SAST Go (Gosec)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      
      - name: Run Gosec Analysis
        run: |
          # Ищем все Go-модули в проекте
          find . -name "go.mod" -exec dirname {} \; | while read dir; do
            echo "Analyzing Go module in $dir"
            cd "$dir"
            ~/go/bin/gosec ./... 2>&1 | tee -a ../gosec-results.txt
            cd -
          done
      
      - name: Upload Go results
        uses: actions/upload-artifact@v4
        with:
          name: sast-go-results
          path: gosec-results.txt

  sast-js:
    name: SAST JavaScript (ESLint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install ESLint security plugin
        run: |
          npm init -y
          npm install eslint eslint-plugin-security --save-dev
      
      - name: Create minimal ESLint config
        run: |
          echo '{
            "plugins": ["security"],
            "rules": {
              "security/detect-object-injection": "error",
              "security/detect-eval-with-expression": "error",
              "security/detect-non-literal-require": "error",
              "security/detect-unsafe-regex": "error"
            }
          }' > .eslintrc.json
      
      - name: Run ESLint security analysis
        run: |
          npx eslint "ui/assets/js/**/*.js" --format=json > eslint-results.json 2>/dev/null || true
      
      - name: Upload JavaScript results
        uses: actions/upload-artifact@v4
        with:
          name: sast-js-results
          path: eslint-results.json

  generate-report:
    name: Generate Summary Report
    runs-on: ubuntu-latest
    needs: [sast-php, sast-c, sast-go, sast-js]
    if: always()
    steps:
      - name: Download all SAST results
        uses: actions/download-artifact@v4
      
      - name: Create HTML summary
        run: |
          echo "<html><body><h1>SAST Results Summary</h1>" > sast-summary.html
          echo "<p>Generated on $(date)</p>" >> sast-summary.html
          
          # PHP Results
          echo "<h2>PHP Analysis</h2>" >> sast-summary.html
          if [ -f "sast-php-results/ui/phpstan-results.txt" ]; then
            echo "<h3>PHPStan:</h3><pre>" >> sast-summary.html
            tail -20 "sast-php-results/ui/phpstan-results.txt" | head -10 >> sast-summary.html
            echo "</pre>" >> sast-summary.html
          fi
          
          # C Results
          echo "<h2>C/C++ Analysis</h2>" >> sast-summary.html
          if [ -f "sast-c-results/cppcheck-results.txt" ]; then
            echo "<h3>Cppcheck (первые 10 предупреждений):</h3><pre>" >> sast-summary.html
            grep -E "(error|warning)" "sast-c-results/cppcheck-results.txt" | head -10 >> sast-summary.html
            echo "</pre>" >> sast-summary.html
          fi
          
          echo "</body></html>" >> sast-summary.html
      
      - name: Upload final report
        uses: actions/upload-artifact@v4
        with:
          name: sast-final-report
          path: |
            sast-summary.html
            sast-php-results/
            sast-c-results/
            sast-go-results/
            sast-js-results/
